//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constantes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Constants.Constantes", typeof(Constantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao executar o método. .
        /// </summary>
        public static string ERRO_EXEC_METODO {
            get {
                return ResourceManager.GetString("ERRO_EXEC_METODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC34601C-803F-4DA4-B4C9-0843AA1E8E4A.
        /// </summary>
        public static string OrdemServicoStatusCancelada {
            get {
                return ResourceManager.GetString("OrdemServicoStatusCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 132AE55D-A544-439E-8D07-CDC643CE4E78.
        /// </summary>
        public static string OrdemServicoStatusEmAndamento {
            get {
                return ResourceManager.GetString("OrdemServicoStatusEmAndamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8330AEC6-5E4D-4B67-8620-0C13FAEC04C5.
        /// </summary>
        public static string OrdemServicoStatusFinalizada {
            get {
                return ResourceManager.GetString("OrdemServicoStatusFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2CF3AF37-18CD-4DF6-BE22-91B4DE792B25.
        /// </summary>
        public static string OrdemServicoStatusIniciada {
            get {
                return ResourceManager.GetString("OrdemServicoStatusIniciada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 642A2B4C-1B28-4857-9FB9-C652B889392B.
        /// </summary>
        public static string OrdemServicoStatusPendente {
            get {
                return ResourceManager.GetString("OrdemServicoStatusPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E4011FE2-1CFC-46A4-9BB7-02F1E154C00E.
        /// </summary>
        public static string OrdemServicoStatusSolicitada {
            get {
                return ResourceManager.GetString("OrdemServicoStatusSolicitada", resourceCulture);
            }
        }
    }
}
